/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Datos.Conexion;
import Logica.Estudiante;
import Logica.Usuario;
import Logica.Principal;
import Interfaz.InicioSesion;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MegaByte
 */
public class MenuEstudiante extends javax.swing.JFrame {
    private int cedula;
    Usuario usuario = new Usuario();
    Estudiante estudiante = new Estudiante();
    private int cedulaActual;
    
    /**
     * Creates new form MenuEstudiante
     */
    public MenuEstudiante(int cedula) {
        initComponents();
        this.cedula = cedula;
        cargarDatos();
    }
    
    private void cargarDatos() {
        usuario.Buscar(cedula);
        estudiante.Buscar(cedula);
        
        System.out.println("Usuario Logeado en menu estudiante: " + Principal.cadulaUsuarioLogeado);

        lblCedula.setText(String.valueOf(usuario.getCedula()));
        lblNombre.setText(usuario.getNombreCompleto());
        lblCorreo.setText(usuario.getCorreoElectronico());
        lblPromedio.setText(String.valueOf(estudiante.getPromedio()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        btnGenerarReporte = new javax.swing.JButton();
        btnExportarPDF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_estudiante_cerrarsesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        lblNombre.setText("[NOMBRE]");

        jLabel3.setText("Cédula:");

        jLabel4.setText("Correo:");

        jLabel5.setText("Promedio:");

        lblCedula.setText("[CEDULA]");

        lblCorreo.setText("[CORREO]");

        lblPromedio.setText("[PROMEDIO]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPromedio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCedula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNombre))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblCedula))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCorreo))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblPromedio))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar información", jPanel1);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Curso", "Nota", "Asistencia", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        btnGenerarReporte.setText("Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnExportarPDF.setText("Exportar PDF");
        btnExportarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnGenerarReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportarPDF)
                .addGap(114, 114, 114))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGenerarReporte)
                    .addComponent(btnExportarPDF))
                .addGap(0, 76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generar reporte", jPanel2);

        btn_estudiante_cerrarsesion.setText("Cerrar sesion");
        btn_estudiante_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudiante_cerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btn_estudiante_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btn_estudiante_cerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cerrar sesión", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_estudiante_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudiante_cerrarsesionActionPerformed
        // TODO add your handling code here:
        InicioSesion ventana = new InicioSesion();
        this.setVisible(false);
        ventana.setVisible(true);
        Principal.cadulaUsuarioLogeado = 0;
    }//GEN-LAST:event_btn_estudiante_cerrarsesionActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
        cargarReporte(cedulaActual);
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnExportarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPDFActionPerformed
        // TODO add your handling code here:
        generarPDF();
    }//GEN-LAST:event_btnExportarPDFActionPerformed

//        public void cargarDatos(int cedula){
//        this.cedulaActual = cedula;
//        
//        Estudiante estudiante = new Estudiante();
//        estudiante.Buscar(cedula);
//        lblNombre.setText(estudiante.getNombreCompleto());
//        lblCedula.setText(String.valueOf(estudiante.getCedula()));
//        lblCorreo.setText(estudiante.getCorreoElectronico());
//        
//        double promedio = estudiante.calcularPromedio();
//        lblPromedio.setText(String.valueOf(promedio));
//    }
//    
    public void cargarReporte(int cedula) {
        Conexion conectar = new Conexion();
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Curso");
        modelo.addColumn("Nota");
        modelo.addColumn("Asistencia (%)");
        modelo.addColumn("Estado");
        
        try {
            String sql = "SELECT c.nombre, a.notaEstudiante, a.asistenciaEstudiante "
                    + "FROM asignacion a "
                    + "INNER JOIN curso c ON a.codigoCurso = c.codigo "
                    + "WHERE a.cedulaEstudiante = ?";

            PreparedStatement pstmt = conectar.Conectar().prepareStatement(sql);
            pstmt.setInt(1,cedula);

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                int nota = rs.getInt("notaEstudiante");
                
                String estado;
                if (nota < 70) {
                    estado = "Riesgo";
                }else{
                    estado = "Aprobado";
                }
                modelo.addRow(new Object[]{
                    rs.getString("nombre"),
                    nota,
                    rs.getInt("asistenciaEstudiante") + "%",
                    estado
                });
            }

            tblReporte.setModel(modelo);

        } catch (Exception e) {
            e.printStackTrace();
        }
}
        public void generarPDF() {
        try {
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream("ReporteEstudiante.pdf"));
            doc.open();

            // 🔹 TÍTULO
            doc.add(new Paragraph("REPORTE ACADÉMICO", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18)));
            doc.add(new Paragraph(" "));

            // 🔹 DATOS DEL ESTUDIANTE (labels que ya tienes)
            doc.add(new Paragraph("Nombre: " + lblNombre.getText()));
            doc.add(new Paragraph("Cédula: " + lblCedula.getText()));
            doc.add(new Paragraph("Correo: " + lblCorreo.getText()));
            doc.add(new Paragraph("Promedio: " + lblPromedio.getText()));
            doc.add(new Paragraph(" "));

            // 🔹 TABLA
            PdfPTable tabla = new PdfPTable(4);
            tabla.addCell("Curso");
            tabla.addCell("Nota");
            tabla.addCell("Asistencia");
            tabla.addCell("Estado");

            Conexion conectar = new Conexion();

            String sql = "SELECT c.nombre, a.notaEstudiante, a.asistenciaEstudiante "
                    + "FROM asignacion a "
                    + "INNER JOIN curso c ON a.codigoCurso = c.codigo "
                    + "WHERE a.cedulaEstudiante = ?";

            PreparedStatement pstmt = conectar.Conectar().prepareStatement(sql);
            pstmt.setInt(1, this.cedulaActual); // 🔥 usamos la misma cédula

            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                int nota = rs.getInt("notaEstudiante");

                String estado;
                if (nota < 70) {
                    estado = "Riesgo";
                } else {
                    estado = "Aprobado";
                }

                tabla.addCell(rs.getString("nombre"));
                tabla.addCell(String.valueOf(nota));
                tabla.addCell(rs.getInt("asistenciaEstudiante") + "%");
                tabla.addCell(estado);
            }

            doc.add(tabla);
            doc.close();

            javax.swing.JOptionPane.showMessageDialog(null, "PDF generado correctamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuEstudiante().setVisible(true);
//            }
//        });
//        
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarPDF;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btn_estudiante_cerrarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
