/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Asignacion;
import Logica.Curso;
import Logica.Estudiante;
import javax.swing.JOptionPane;

/**
 *
 * @author MegaByte
 */
public class MenuDocente extends javax.swing.JFrame {

    /**
     * Creates new form MenuDocente
     */
    public MenuDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_gestionarestudiante_codigocurso = new javax.swing.JTextField();
        txt_gestionarestudiante_codigoEstudiante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_gestionarestudiante_notacurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_gestionarestudiante_asistenciacurso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código del curso:");

        jLabel2.setText("Código del estudiante:");

        jLabel3.setText("Nota del curso:");

        jLabel4.setText("Asistencia del curso:");

        jButton1.setText("Actualizar información");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gestionarestudiante_asistenciacurso, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gestionarestudiante_notacurso, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txt_gestionarestudiante_codigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_gestionarestudiante_codigocurso, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton1)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_gestionarestudiante_codigocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_gestionarestudiante_codigoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_gestionarestudiante_notacurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_gestionarestudiante_asistenciacurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestionar estudiante", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver alertas", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Generar reporte", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int codigoCurso = Integer.parseInt(txt_gestionarestudiante_codigocurso.getText());
        int cedulaEstudiante = Integer.parseInt(txt_gestionarestudiante_codigoEstudiante.getText());
        int nota = Integer.parseInt(txt_gestionarestudiante_notacurso.getText());
        int asistencia = Integer.parseInt(txt_gestionarestudiante_asistenciacurso.getText());
        
       
        
        Asignacion objAsignacion = new Asignacion();
        

        
        //Estudiante estudanteBuscado = new Estudiante();
        //Curso cursoBuscado = new Curso();
        
        objAsignacion.Buscar(cedulaEstudiante, codigoCurso);
        objAsignacion.setNota(nota);
        objAsignacion.setAsistencia(asistencia);

        //estudanteBuscado.Buscar(cedulaEstudiante);
        //cursoBuscado.Buscar();
        
        

        System.out.println("cedulaEstudiante " + objAsignacion.getCedulaEstudiante());
        if (objAsignacion.getCedulaEstudiante() == 0) { //No existe, hay que crear
            objAsignacion.setCedulaEstudiante(cedulaEstudiante);
            objAsignacion.setCodigoCurso(codigoCurso);
            objAsignacion.Agregar();
            JOptionPane.showMessageDialog(null, "Se asigno el usuario " + cedulaEstudiante + " al curso seleccionado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } else { //existe, hay que editar
            objAsignacion.Actualizar();
            JOptionPane.showMessageDialog(null, "Se actualizaron datos del estudiante " + cedulaEstudiante, "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        }
        
        /*if (objAsignacion.getCedulaEstudiante() == 0) { //No existe la asignacion aun
            if (nota < 0 || nota > 100) {
                JOptionPane.showMessageDialog(null, "Nota con valores invalidos, favor ingresar otro dato", "Error en nota", JOptionPane.ERROR_MESSAGE);
            } else {
                if (asistencia < 0) {
                    JOptionPane.showMessageDialog(null, "Asistencia con valores invalidos, favor ingresar otro dato", "Error en asistencia", JOptionPane.ERROR_MESSAGE);
                } else {
                    objAsignacion.Agregar();
                    JOptionPane.showMessageDialog(null, "Se asigno el usuario " + cedulaEstudiante + " al curso seleccionado", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            if (nota < 0 || nota > 100) {
                JOptionPane.showMessageDialog(null, "Nota con valores invalidos, favor ingresar otro dato", "Error en nota", JOptionPane.ERROR_MESSAGE);
            } else {
                if (asistencia < 0) {
                    JOptionPane.showMessageDialog(null, "Asistencia con valores invalidos, favor ingresar otro dato", "Error en asistencia", JOptionPane.ERROR_MESSAGE);
                } else {
                    objAsignacion.Actualizar();
                    JOptionPane.showMessageDialog(null, "Se actualizaron datos del estudiante " + cedulaEstudiante, "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_gestionarestudiante_asistenciacurso;
    private javax.swing.JTextField txt_gestionarestudiante_codigoEstudiante;
    private javax.swing.JTextField txt_gestionarestudiante_codigocurso;
    private javax.swing.JTextField txt_gestionarestudiante_notacurso;
    // End of variables declaration//GEN-END:variables
}
